# github workflow to make a release
name: Create release based on a tag
on:
  push:
    tags:
      - 'v*' # Trigger when a tag like v1.0.0 is pushed
permissions:
  contents: write # Grants write permission to repository contents

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: './dist'
          filename: xrpweb-v${{ github.run_number }}
      - name: Create Release
        id: create_new_release
        uses: softprops/action-gh-release@v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./xrpweb-v${{ github.run_number }}.zip
          asset_name: xrpweb-v${{ github.run_number }}.zip
          asset_content_type: application/zip



